#+title: John Eismeier Resume
#+AUTHOR: John Eismeier
#+KEYWORDS: vita, CV, resume
#+OPTIONS: toc:nil num:nil :noexport:
#+STARTUP: entitiespretty


* John Eismeier
#+attr_html: :class mytable meta :rules all :border nil :cellspacing nil :cellpadding nil :frame nil
#+attr_latex: :align c|c|c|c
| [[mailto:email@gmail.com][john.eismeier@yahoo.com]] | [[https://linkedin.com/in/username][linkedin.com/in/johneismeier]] | +1-5086357384  | Worcester, Massachusetts |


* Summary
  :PROPERTIES:
  :header-args: :tangle no
  :END:
  Seeking to champion Linux/HPC/ai/CFD/WebWork/Virtuoso/Calibre/R/Comsol in an academic setting.

* Professional Experience
  :PROPERTIES:
  :header-args: :tangle no
  :END:
  - **System Engineer III** - Worcester Polytechnic Institute - [2018-2025]
    - Teach Linux command line interface introduction supporting students academics.
    - Teach High Performance Computing SLURM introduction enabling research.
    - Enable researchers with software like gprMax, Gurobi, COMSOL, Fluent, SimVascular in HPC environment.
    - Deploy/Champion WebWork as needed for Placement, Calculus, statistics and additional course work.
    - Transform WebWork with grade passing LTI integration to canvas.
    - Offer Red Hat Academy courses self paced for students.
    - Manage Cadence/Mentor Virtuoso/Calibre ECE design and research infrastructure.
    - Provide DNA, RNA, protein sequencing for course work and research.
    - Deploy slice constraints managing VScode CPU hogging and classic fork bombs.
    - Deploy research driven spack software installs in HPC SLURM environment.
    - Provide guidance on research approach utilizing HPC resources for academic goals.
    - Deploy chronyd for updated time synchronization solution for the campus.
    - Manage R1 HPC research cluster with 5k+ CPU/49T RAB/84 GPU and SLURM with PXE image boot/patch management
    - Deploy and Manage RHEL/Ubuntu Infrastructure

  - **Scrum Master** - Dell/EMC Corporation - [2014-2017]
    - Encouraged VPLEX build team delivering
    - Introduce Jenkins/Artifactory to replace legacy product build system with common off the shelf tooling improving build time from 8 hours to 2 hours reliably.
    - Matured new Jenkins/Artifactory build system so that Product Managers were enabled to create product releases to partners and customers.
    - Completed migration from legacy Cloud to next generation Cloud Native with near zero downtime of development and release services provided.
    - Site Reliability contributor configuring Nagios for all critical servers/services in new Cloud Native infrastructure.
    - Improved code quality and received "Silver Award of Excellence" by developing automation using Coverity static analysis tools to block defect introduction during code commit.
    - Consumed Gitlab CE/EE as continuously delivered product by frequent Gitlab deployments via Puppet providing bug fixes, added features, i.e. squash commits.
    - Transform product defect tracking from legacy ClearQuest to JIRA keeping a backlog of must fix issues that were exposed to leadership team.  Provided operational support/assignment migrating to JIRA.
    - Safeguarded project/product resources by managing access controls of colleagues that left by driving defect reassignments guided by leadership input.
    - Performed Scrum Master rituals; daily stand up, planned sprints, reviews, and fun retrospective; provided value to business with each sprint; published progress team completed, ensuring staff could learn, review and speed up product delivery.
    - Enabled team members to develop and contribute to product deliverable goals by reviewing and repairing Nagios/Puppetboard reported issues of infrastructure daily.
    - Certified delivery of new product was ready for release during every code commit by providing new end-to-end pipeline support in Jenkins of 30-day monitoring appliance.
    - Protected infrastructure from Ransomware and improved product by repairing HeartBleed, WannaCry and ShellShock issues and managing vulnerabilities for developers and products.
    - FOSS/Blackduck process contributor and earlier adopter socializing how to use; increasing legal approval time of FOSS integration into product.

  - **Principal Build / Release Engineer** - Dell/EMC Corp. - [2012-2013]
    - Proposed Tableau reporting after BI tools evaluation of TIBCO, Pentaho, Tableau; Built server/desktop infrastructure that successfully replaced spreadsheet management.
    - Developed email push automation to mobile devices on daily Tableau reports, keeping management informed of progress and meeting business objectives established each quarter.
    - Learned and mentored current home grown VPLEX build / release platform, keeping software products released to customers.
    - Regular security audit implementing best practice post 2011 hack driving patch management processes and vulnerability assessments.
    - Created WPAtools virtual appliance with KIWI build tools SuSE/SLES JeOS platform. Portable disposable web for NetAPP hot spots used in dark / secure data centers. Appliance was patched with seccheck and NESSUS credentialed STIG scan for security application and appliance hardening.
    - Ensured appliance shipment by completing legal compliance and patent review requirements for third-party, expanding VPLEX spreadsheet for legal with VMware branding.
    - "Gold Award of Excellence" for the delivery and support of the WPAtools appliance packaged on a thumb drive.  This appliance included collaboration with Mitrend.  The appliance incorporated XFS, PVSCSI, VMXNET3 drivers for optimization of the analysis and reporting.
    - Site Reliability contributor deploying and management of ESXi servers, Virtual Machines, security patching and hardware replacement.
    - Created automation for ClamAV daily product scans migrating away from legacy McAfee reporting deficiencies to Corporate IT and McAfee.
    - "Silver Award of Excellence" for GIT SCM migration proposal replacing legacy CVS solution.

  - **Senior Linux Engineer** - MONSTER WORLDWIDE, Maynard, MA - [2011-2012]
  - **Principal Release Engineer** - [START UP COMPANY, Westborough, MA] - [2010]
  - **EDA / Tools and Infrastructure Engineer** - EMC Corporation, Hopkinton, MA
  - **Senior Software Tools and Infrastructure Engineer** - CLARiiON, Westborough, MA
  - **Senior Software Tools Engineer** - BOSTON TECHNOLOGY, Wakefield, MA
  - **Senior Software Tools Engineer** - GE AIRCRAFT, Lynn, MA
  - **Senior Engineer** - RILEY STOKER, Worcester, MA
  - **Mechanical Engineer** - COPPUS ENGINEERING CORP., Worcester, MA

* Education
  :PROPERTIES:
  :header-args: :tangle no
  :END:
  - **[Masters of Science (MS)]** - [Worcester Polytechnic Institute (WPI), Worcester, MA]
  - **[Bachelor of Science (BS)]** - [Worcester Polytechnic Institute (WPI), Worcester, MA]

* Skills
  :PROPERTIES:
  :header-args: :tangle no
  :END:
  - **Languages**: Python, Bash, Puppet, Ansible, YAML, Rake, Make, Cmake, Ruby, SQL, HTML, NodeJS, Maven, Ant, RPM,DPKG, GNU tools, Zypper, dnf
  - **Platforms**: HPC/ai, Gitlab, VMware/Proxmox/Nutanix, Docker/Apptainer containers, Ubuntu, RedHat, CentOS, SLES,Alpine, Windows, Solaris, HPUX, AIX, Cloud
  - **Applications**: Jenkins, Gitlab CE/EE, Puppet, Ansible, JIRA, Artifactory, Blackduck, ClamAV, DNS, SAN, NAS, LDAP,Github,WeBWork
  - **Databases**: Postgresql, MySQL, Redis, Xapian, MSSQL
  - **Tools**: Gitlab, Coverity, Tableau, JIRA, Nessus STIG, Sonar, Artifactory, Nagios, Cacti, Munin, ossec, Bro,  KIWI, VMware studio, Bullseye, clamscan, savscan, ESET, splunk
  - **Other**: Scrum Master for DevOps and LabOps team, Mentor, Security Vulnerability Management, Open Source Contributor

